export enum Path {
  AddReview = '/add',
  Avatar = '/avatar',
  Favorites = '/favorites',
  Login = '/login',
  Main = '/',
  MovieID = '/:movieID',
  Movies = '/movies',
  Promo = '/promo',
  Register = '/register',
  Reviews = '/reviews',
  Upload = '/upload',
  UserID = '/:userID',
  Users = '/users',
}
